import { describe, it, expect, vi, beforeEach } from 'vitest';
import { Decimal } from 'decimal.js';
import { AuditActionType, SplitType, MembershipEventType } from '@prisma/client';
import { AuditService } from '../../services/AuditService';
import { AuditLogRepository } from '../../repositories/audit.repo';
import { ExpenseService } from '../../services/ExpenseService';
import { SettlementService } from '../../services/SettlementService';
import { GroupService } from '../../services/group';
import { prisma } from '../../lib/prisma';

// Mock the prisma client singleton
vi.mock('../../lib/prisma', () => {
  return {
    prisma: {
      auditLog: { create: vi.fn(), findMany: vi.fn(), count: vi.fn() },
      user: { findUnique: vi.fn() },
      groupMembership: { findUnique: vi.fn() },
      expense: { create: vi.fn(), findFirst: vi.fn(), update: vi.fn() },
      settlement: { create: vi.fn(), findUnique: vi.fn(), update: vi.fn() },
      $transaction: vi.fn((cb) => cb(prisma)),
    },
  };
});

describe('Audit Trail Architecture & Centralized Logging', () => {
  let mockAuditRepo: any;
  let auditService: AuditService;

  beforeEach(() => {
    vi.clearAllMocks();
    mockAuditRepo = {
      create: vi.fn().mockResolvedValue({ id: 'log-123' }),
    };
    auditService = new AuditService(mockAuditRepo as unknown as AuditLogRepository);
  });

  describe('AuditService Diffing Logic', () => {
    it('should correctly calculate diff for simple field updates', () => {
      const before = { description: 'Rent', amount: 5000, date: new Date('2026-03-01') };
      const after = { description: 'Rent March', amount: 5500, date: new Date('2026-03-01') };
      
      const diff = auditService.calculateDiff(before, after);
      expect(diff).not.toBeNull();
      expect(diff!.amount.before).toBe(5000);
      expect(diff!.amount.after).toBe(5500);
      expect(diff!.description.before).toBe('Rent');
      expect(diff!.description.after).toBe('Rent March');
      expect(diff!.date).toBeUndefined(); // Unchanged
    });

    it('should ignore autogenerated timestamp columns in diff comparison', () => {
      const before = { id: '1', createdAt: new Date('2026-02-01') };
      const after = { id: '1', createdAt: new Date('2026-03-01'), updatedAt: new Date() };

      const diff = auditService.calculateDiff(before, after);
      expect(diff).toBeNull(); // No key business changes
    });
  });

  describe('Best-Effort Failure Tolerance (Never block operations)', () => {
    it('should swallow write errors in AuditService and not throw to caller', async () => {
      mockAuditRepo.create.mockRejectedValueOnce(new Error('DB Connection Timeout'));
      
      const log = await auditService.logEvent({
        actorId: 'u-1',
        action: AuditActionType.CREATE_EXPENSE,
        entityType: 'EXPENSE',
        entityId: 'e-1',
      });
      
      expect(log).toBeNull(); // Swallowed correctly
    });
  });

  describe('Domain Service Integration Auditing', () => {
    let mockExpenseRepo: any;
    let mockSplitCalc: any;
    let mockExchangeRate: any;
    let mockMembership: any;
    let expenseService: ExpenseService;

    let mockSettlementRepo: any;
    let settlementService: SettlementService;

    let mockGroupRepo: any;
    let groupService: GroupService;

    beforeEach(() => {
      // Mock Expense Dependencies
      mockExpenseRepo = {
        createExpense: vi.fn().mockResolvedValue({ id: 'exp-1', originalAmount: new Decimal(100) }),
        findExpenseById: vi.fn().mockResolvedValue({ id: 'exp-1', groupId: 'g-1', paidById: 'u-1', originalAmount: new Decimal(100) }),
        softDeleteExpense: vi.fn().mockResolvedValue({ id: 'exp-1', deletedAt: new Date() }),
        updateExpense: vi.fn().mockResolvedValue({ id: 'exp-1', originalAmount: new Decimal(120) }),
      };
      mockSplitCalc = { calculateSplits: vi.fn().mockReturnValue([]) };
      mockExchangeRate = {
        convertToBase: vi.fn().mockResolvedValue({
          convertedAmount: new Decimal(8350),
          exchangeRate: new Decimal(83.5),
        }),
      };
      mockMembership = { isUserActiveOnDate: vi.fn().mockResolvedValue(true) };

      const mockBalanceEngine = {
        rebuildSnapshot: vi.fn().mockResolvedValue({}),
      };

      expenseService = new ExpenseService(
        mockExpenseRepo,
        mockSplitCalc,
        mockExchangeRate,
        mockMembership,
        auditService,
        mockBalanceEngine as any
      );

      // Mock Settlement Dependencies
      mockSettlementRepo = {
        createSettlement: vi.fn().mockResolvedValue({ id: 'settle-1' }),
        findSettlementById: vi.fn().mockResolvedValue({ id: 'settle-1', groupId: 'g-1', senderId: 'u-1', receiverId: 'u-2' }),
        updateSettlement: vi.fn().mockResolvedValue({ id: 'settle-1', amount: new Decimal(6000) }),
        deleteSettlement: vi.fn().mockResolvedValue({ id: 'settle-1' }),
      };
      settlementService = new SettlementService(
        mockSettlementRepo,
        mockExchangeRate,
        mockMembership,
        auditService,
        mockBalanceEngine as any
      );

      // Mock Group Dependencies
      mockGroupRepo = {
        findGroupByName: vi.fn().mockResolvedValue(null),
        createGroup: vi.fn().mockResolvedValue({ id: 'g-1', name: 'Flat' }),
        findGroupById: vi.fn().mockResolvedValue({ id: 'g-1' }),
        addMemberToGroup: vi.fn(),
        removeMemberFromGroup: vi.fn(),
        createMembershipHistory: vi.fn().mockResolvedValue({ id: 'hist-1' }),
      };
      groupService = new GroupService(mockGroupRepo, auditService);
    });

    it('should log CREATE_EXPENSE audit entry on createExpense', async () => {
      await expenseService.createExpense({
        groupId: 'g-1',
        paidById: 'u-1',
        description: 'Rent',
        originalAmount: 100,
        originalCurrency: 'USD',
        date: new Date(),
        splitType: SplitType.EQUAL,
        participants: [{ userId: 'u-1' }],
      }, 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.CREATE_EXPENSE,
          entityType: 'EXPENSE',
          entityId: 'exp-1',
          userId: 'u-1',
        })
      );
    });

    it('should log UPDATE_EXPENSE and calculate diff on updateExpense', async () => {
      await expenseService.updateExpense('exp-1', {
        description: 'Rent updated',
        originalAmount: 120,
        originalCurrency: 'USD',
        date: new Date(),
        splitType: SplitType.EQUAL,
        participants: [{ userId: 'u-1' }],
      }, 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.UPDATE_EXPENSE,
          entityType: 'EXPENSE',
          entityId: 'exp-1',
          userId: 'u-1',
        })
      );
    });

    it('should log DELETE_EXPENSE audit entry on deleteExpense', async () => {
      await expenseService.deleteExpense('exp-1', 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.DELETE_EXPENSE,
          entityType: 'EXPENSE',
          entityId: 'exp-1',
          userId: 'u-1',
        })
      );
    });

    it('should log CREATE_SETTLEMENT audit entry on createSettlement', async () => {
      await settlementService.createSettlement({
        groupId: 'g-1',
        senderId: 'u-1',
        receiverId: 'u-2',
        amount: 5000,
        currency: 'INR',
        date: new Date(),
      }, 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.CREATE_SETTLEMENT,
          entityType: 'SETTLEMENT',
          entityId: 'settle-1',
          userId: 'u-1',
        })
      );
    });

    it('should log UPDATE_SETTLEMENT audit entry on updateSettlement', async () => {
      await settlementService.updateSettlement('settle-1', {
        amount: 6000,
        currency: 'INR',
        date: new Date(),
      }, 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.UPDATE_SETTLEMENT,
          entityType: 'SETTLEMENT',
          entityId: 'settle-1',
          userId: 'u-1',
        })
      );
    });

    it('should log CREATE_GROUP audit entry on createGroup', async () => {
      await groupService.createGroup('Flat', 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.CREATE_GROUP,
          entityType: 'GROUP',
          entityId: 'g-1',
          userId: 'u-1',
        })
      );
    });

    it('should log MEMBER_JOIN audit entry on addMember', async () => {
      await groupService.addMember('g-1', 'u-sam', new Date(), 'Sam joined', 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.MEMBER_JOIN,
          entityType: 'MEMBERSHIP',
          entityId: 'hist-1',
          userId: 'u-1',
        })
      );
    });

    it('should log MEMBER_LEAVE audit entry on removeMember', async () => {
      await groupService.removeMember('g-1', 'u-meera', new Date(), 'Meera left', 'u-1');

      expect(mockAuditRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          action: AuditActionType.MEMBER_LEAVE,
          entityType: 'MEMBERSHIP',
          entityId: 'hist-1',
          userId: 'u-1',
        })
      );
    });
  });
});
